* My rcfiles collection 

  Thanks to [[https://github.com/pi314][pi314]] and friends in nba/nctu, now I use github to manage my rcfiles. The setup.sh copied from [[https://github.com/pi314/rcfiles][pi314 rcfiles]].

  A portable solution for UNIX-like machine (Linux, FreeBSD, Cygwin, Mac OS X, etc.) and a reminder for everyone when to install a new system. 


* Other rcfiles I use

Those rcfiles are my favourites, people have higher understanding about tools they code. I cannot find any reason not to use those tools to make things easier when I do not have time to learn that much. I would install them before using my rcfiles.

  git as listed:
  
  - Prezto for zsh : https://github.com/sorin-ionescu/prezto
  - Agonster Prompt for Prezto (optional) : https://github.com/mozeroman/zsh.prompts
  - Percol : https://github.com/mooz/percol  
  - Emacs : https://github.com/redguardtoo/emacs.d
  - Fasd : https://github.com/clvv/fasd


  non-git plugins as listed:

  - Vimperator for firefox
  - devilspie for linux - a window manager at startup

    
* Installation

Download zip file from github or using the command below:

- For everyone:

  1. cd 
  2. git clone https://github.com/mozeroman/rcfiles.git .rcfiles
  3. sh ~/.rcfiles/setup.sh

- Or ssh way (note for myself):

  1. cd
  2. git clone git@github.com:mozeroman/rcfiles.git .rcfiles
  3. sh ~/.rcfiles/setup.sh

Old rcfiles will be backuped in ~/.old_rcfiles/ with timestamp, after these configuration file being installed. 

Remember to change the user data in .gitconfig (or delete it), to add/delete resource files.


* Files in rcfiles

** setup.sh

   shell commands to make soft links from .rcfiles to ~/

** .gitconfig

   git settings, using vim as editor

** .zshrc and .zsh/
   
  trying to make Zsh/Prezto work better, .zshrc only links to files in .zsh/ for better organizing

- foragnoster.zsh
  function used in agonster
- myfunctions.zsh
  my shell settings & shell functions, combine programs as a single command, example: copy(), lls()
- alias.zsh
  my personal alias
- percol.zsh
  percol-settings in zsh from offical guide, e.g.: C-r searching .history
- fasd.zsh
  fasd combine with zsh, making fd ff fa function to quick select files/dir for other programs


** .vimrc

   my tiny vimrc, only for viewing and simple editing

** .percol.d/rc.py

   emacs like key-binding and other functions recommend in [[https://github.com/mooz/percol][mooz/percol]]

** .custom.el and .myemacs.d/

   customize emacs setting besides [[https://github.com/redguardtoo/emacs.d][redguardtoo/emacs.d]]

- my-org.el
  setting up MobileOrg, org-publish and org-agenda links to GTD.org only
- molokai-theme-kit.el
  improve color-theme-molokai, edited from hbin/molokai-theme

** .vimperatorrc

   customizing key-bindings in vimperator for firefox

** .devilspie/

   customizing devilspie with my usual applications
   

   