* My rcfiles collection 

  Thanks to [[https://github.com/pi314][pi314]] and friends in nba/nctu, now I use github to manage my rcfiles. The setup.sh mostly copied from [[https://github.com/pi314/rcfiles][pi314 rcfiles]].
  I am trying to make it a portable solution for UNIX-like machine (Linux, FreeBSD, Cygwin, Mac OS X, etc.) and make it a reminder for myself if I have to install a new system.


* Other rcfiles I use

Those rcfiles are my favourites, people have higher understanding about tools they code. I cannot find any reason not to use those tools to make things easier when I do not have time to learn that much. I would install them before using my rcfiles.

  git as listed:
  
  - Prezto for zsh : https://github.com/sorin-ionescu/prezto
  - Agonster Prompt for Prezto (optional) : https://github.com/mozeroman/zsh.prompts
  - Percol : https://github.com/mooz/percol  
  - Emacs : https://github.com/redguardtoo/emacs.d

  non-git plugins as listed:

  - Vimperator for firefox
  - devilspie for applications automatic management to workspace


* Installation

Download zip file from github or using the command below:

- For everyone:

  1. cd 
  2. git clone https://github.com/mozeroman/rcfiles.git .rcfiles
  3. sh ~/.rcfiles/setup.sh

- Or ssh way for myself (change [mozeorman] to [yourusername]):

  1. cd
  2. git clone git@github.com:mozeroman/rcfiles.git .rcfiles
  3. sh ~/.rcfiles/setup.sh

Old rcfiles will be backuped in ~/.old_rcfiles/ with timestamp, after these configuration file being installed. 

Remember to change the user data in .gitconfig (or delete it), to add/delete resource files.


* Files in rcfiles

** setup.sh

   shell commands to make soft links from .rcfiles to ~/

** .gitconfig

   git settings, using vim as editor

** .zshrc and .zsh/
   
   make Zsh/Prezto better

- .foragnoster.zsh
  function used in agonster
- .myfunctions.zsh
  my sh functions, like copy()
- .alias.zsh
  my personal alias
- .percol.zsh
  percol combine with zsh, like C-r searching .history

** .vimrc

   my tiny vimrc, only for viewing and simple editing

** .percol.d/rc.py

   emacs like key-binding and other functions recommend in [[https://github.com/mooz/percol][mooz/percol]]

** .custom.el and .myemacs.d/

   customize emacs setting besides [[https://github.com/redguardtoo/emacs.d][redguardtoo/emacs.d]]

- my-org.el
  setting up MobileOrg, org-publish and org-agenda links to GTD.org only
- my-eim.el
  setting ,. for pageup/pagedown the input seletion bar
- molokai-theme-kit.el
  improve color-theme-molokai, edited from hbin/molokai-theme

** .vimperatorrc

   customizing key-bindings in vimperator for firefox

** .devilspie/

   customizing devilspie with my usual applications
   